### ISSUE TITLE
Merge other forks?

### ISSUE THREAD

**Issue by k-takata** [k-takata/lv-mod#2]
- [x] https://github.com/mattn/lv-windows  
  @mattn's windows port
- [x] https://github.com/amuramatsu/lv-mod  
  @amuramatsu's windows port
- [x] http://anonscm.debian.org/cgit/collab-maint/lv.git  
  Debian's repository

**Comment by mattn** [comment]
:+1:

**Comment by amuramatsu** [comment]
good idea

**Comment by k-takata** [comment]
`topic/merge-amuramatsu` ブランチでマージ作業中。

**Comment by k-takata** [comment]
amuramatsu さんの変更はブランチにほぼ取り込んだつもり。

**Comment by k-takata** [comment]
Debian関連のファイルも最新のものに更新完了。
`configure`スクリプトを`src`からトップディレクトリに移動した影響で、いくつかのファイルに変更が必要と思われるが、今回は特に対応はしていない。

**Comment by k-takata** [comment]
masterにマージ完了。

**Comment by k-takata** [comment]
Just FYI, Debian's repository was moved to https://salsa.debian.org/debian/lv.git .
